-- CreateEnum
CREATE TYPE "public"."Licenciatura" AS ENUM ('NO_APLICA', 'CONTADOR_PUBLICO', 'ADMINISTRACION', 'INFORMATICA', 'ADMINISTRACION_PUBLICA', 'ECONOMIA', 'ADMINISTRACION_POLITICAS_PUBLICAS');

-- AlterTable
ALTER TABLE "public"."User" ADD COLUMN     "licenciatura" "public"."Licenciatura" NOT NULL DEFAULT 'NO_APLICA';
